import "./globals.css";
import Link from "next/link";
import "bootstrap/dist/css/bootstrap.min.css";
import "remixicon/fonts/remixicon.css";
import { AuthContextProvider } from "./context/AuthContext";

import CentralData from "./Context";
import { ThemeProvider } from "../app/context/themeContext";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Giphy Api",
  description: "Generated by create next app",
};

const Authentication = (props) => {
  const { children } = props;
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}>
        <AuthContextProvider>
          <CentralData>
            <ThemeProvider>
              <Navbar />
              {children}
              </ThemeProvider>
          </CentralData>
        </AuthContextProvider>
      </body>
    </html>
  );
};

export default Authentication;
